-- yajuter on Supabase / Postgres schema
-- ============================================================
-- MySQL (XAMPP) からの移植版。初回のみ Supabase SQL Editor で実行。
-- 方針:
--   * ID は GENERATED BY DEFAULT AS IDENTITY（移行時の明示ID挿入を許可。
--     posts は 114515〜、pilgrimage_logs/events は 811〜 を温存する）
--   * 本番データ移行後に各シーケンスを setval すること
--     （scripts/migrate-from-mysql.mjs が自動で行う）
--   * RLS は有効化するが anon 向けポリシーは作らない。
--     全アクセスは Next.js の API Routes 経由（service_role）で行う。
--     ＝単独ゲート（Middlewareパスワード）＋サーバ経由の二重防御。
--     CGM化（多人数）時に Supabase Auth + user スコープポリシーへ拡張する。
-- ============================================================

-- ================= users =================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  bio VARCHAR(200) NOT NULL DEFAULT '',
  avatar_emoji VARCHAR(16) NOT NULL DEFAULT '野',
  theme VARCHAR(20) NOT NULL DEFAULT 'yaju-gold',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================= posts =================
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  content TEXT NOT NULL,
  emotion_tag VARCHAR(20) DEFAULT NULL,
  image_path VARCHAR(255) DEFAULT NULL,
  like_count INT NOT NULL DEFAULT 0,
  bookmarked BOOLEAN NOT NULL DEFAULT FALSE,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  reply_to BIGINT DEFAULT NULL REFERENCES posts(id),
  scheduled_at TIMESTAMPTZ DEFAULT NULL,
  edited_at TIMESTAMPTZ DEFAULT NULL,
  deleted_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_posts_created ON posts (created_at);
CREATE INDEX IF NOT EXISTS idx_posts_user_date ON posts (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_posts_reply_to ON posts (reply_to);

-- ================= pilgrimage =================
CREATE TABLE IF NOT EXISTS pilgrimage_spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  area VARCHAR(100) NOT NULL,
  description TEXT,
  caution TEXT NOT NULL,
  is_public BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS pilgrimage_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  spot_id BIGINT NOT NULL REFERENCES pilgrimage_spots(id),
  visited_at DATE NOT NULL,
  digital_only BOOLEAN NOT NULL DEFAULT TRUE,
  memo TEXT,
  photo_path VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================= anniversaries / events =================
CREATE TABLE IF NOT EXISTS anniversaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  month SMALLINT NOT NULL,
  day SMALLINT NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  title VARCHAR(200) NOT NULL,
  event_date DATE NOT NULL,
  memo TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================= quotes =================
CREATE TABLE IF NOT EXISTS quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text VARCHAR(200) NOT NULL,
  reading VARCHAR(200) DEFAULT NULL,
  category VARCHAR(30) DEFAULT 'imn',
  source VARCHAR(100) DEFAULT NULL,
  meaning TEXT,
  usage_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================= badges =================
CREATE TABLE IF NOT EXISTS badges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(200) NOT NULL,
  icon VARCHAR(8) NOT NULL,
  threshold INT NOT NULL DEFAULT 1,
  metric VARCHAR(30) NOT NULL,
  rarity VARCHAR(10) DEFAULT 'normal'
);

CREATE TABLE IF NOT EXISTS badge_unlocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  badge_code VARCHAR(50) NOT NULL,
  seen BOOLEAN NOT NULL DEFAULT FALSE,
  unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, badge_code)
);

-- ================= search_history / settings =================
CREATE TABLE IF NOT EXISTS search_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  query VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  user_id BIGINT PRIMARY KEY REFERENCES users(id),
  theme VARCHAR(20) NOT NULL DEFAULT 'yaju-gold',
  daily_goal INT NOT NULL DEFAULT 1,
  quiz_best_hard INT NOT NULL DEFAULT 0
);

-- ================= post_stamps =================
CREATE TABLE IF NOT EXISTS post_stamps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  stamp VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (post_id, stamp)
);

-- ================= notices =================
CREATE TABLE IF NOT EXISTS notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'info' CHECK (kind IN ('info', 'culture', 'update')),
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================= RLS（anon 拒否・service_role のみ） =================
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE pilgrimage_spots ENABLE ROW LEVEL SECURITY;
ALTER TABLE pilgrimage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE anniversaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE badge_unlocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_stamps ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
-- ※ ポリシーを作らない＝anon/authenticated ロールは一切触れない。
--    service_role は RLS をバイパスするので API Routes から利用可。

-- ================= Storage buckets =================
INSERT INTO storage.buckets (id, name, public)
VALUES ('uploads', 'uploads', FALSE),
       ('pilgrimage', 'pilgrimage', FALSE)
ON CONFLICT (id) DO NOTHING;

-- ================= 初期データ =================
INSERT INTO users (id, username, display_name, bio)
VALUES (1, 'watashi', '私（1人用モード）', '野獣先輩を推すためのyajuter')
ON CONFLICT (id) DO NOTHING;

INSERT INTO settings (user_id, theme, daily_goal)
VALUES (1, 'yaju-gold', 1)
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO pilgrimage_spots (name, area, description, caution) VALUES
('野獣邸（外観のみ）', '東京都世田谷区下北沢周辺', '淫夢四章のロケ地として知られる場所。※COAT社は8月10日に関するお願いで「所在地やその近隣にお越しになることはお止めいただきますよう」と明言しています。現地に行く場合は近隣住民・警備員への配慮を最優先に。', '撮影禁止（4か国語の看板あり）。8/10前後は厳戒態勢。近隣迷惑行為は警察沙汰になります。絶対にやめましょう。基本的にはデジタル巡礼で。'),
('北沢三丁目公園（周辺）', '東京都世田谷区下北沢', '野獣邸周辺の公園。※過去に巡礼客のトラブルが実際に起きている場所。デジタル巡礼を推奨。', '屯・騒音・コスプレは禁止。近隣住民の生活空間です。'),
('下北沢（街全体）', '東京都世田谷区', '淫夢文化ゆかりの街。ただし普通に住んでいる人がいる街でもある。', '聖地巡礼マナーを守って。迷惑行為はファン全体の評判を落とします。');

INSERT INTO anniversaries (name, month, day, description) VALUES
('野獣の日', 8, 10, '810（やじゅう）。※COAT社が定めた記念日ではなく、同社は聖地巡礼を自粛するよう呼びかけています。自宅で「せーのっ…こ↑こ↓！」と唱えるのが文化。'),
('真夏の夜の淫夢 発売記念日', 7, 20, '2001年7月20日発売。Babylon STAGE 34。'),
('いいよ、来いよ の日', 1, 14, '114514の頭「いいよ（1/14）」。11時45分14秒に何かをするのが習わし。'),
('イキスギィの日', 9, 19, '1919（いくいく）。'),
('微レ存の日', 4, 5, '微粒子レベルで存在している…？（ビレゾンの日）');

INSERT INTO badges (code, name, description, icon, threshold, metric, rarity) VALUES
('first_post', 'やったぜ。', '初投稿を達成', '初', 1, 'post_count', 'normal'),
('post_810', '810記念', '投稿数が810回に到達', '810', 810, 'post_count', 'legend'),
('post_100', 'やりますねぇ!', '投稿数が100回に到達', '百', 100, 'post_count', 'rare'),
('post_500', '迫真の声援', '投稿数が500回に到達', '五', 500, 'post_count', 'epic'),
('chars_114514', 'いいよ、こいよ', '総投稿文字数が114514文字に到達', '1', 114514, 'total_chars', 'legend'),
('chars_10000', '語録の伝道師', '総投稿文字数が10000文字に到達', '万', 10000, 'total_chars', 'rare'),
('streak_8', 'やりますねぇ!', '8日連続投稿を達成', '連', 8, 'streak_days', 'rare'),
('streak_81', '迫真空手部', '81日連続投稿を達成', '道', 81, 'streak_days', 'epic'),
('yajuday_post', '野獣の日参加', '8月10日に投稿した（自宅から）', '獣', 1, 'yajuday_post', 'epic'),
('pilgrimage_1', '†巡礼者†', '巡礼ログを初めて記録', '†', 1, 'pilgrimage_count', 'normal'),
('pilgrimage_810', 'デジタル野獣', '巡礼ログが810回に到達', '獣', 810, 'pilgrimage_count', 'legend'),
('event_1', 'じゃけん予定しましょうね', '予定を初めて登録', '予', 1, 'event_count', 'normal'),
('like_1', 'いいゾ〜これ', '投稿にいいぞをつけた', '©', 1, 'like_count_total', 'normal'),
('like_810', '完全に理解した', 'いいぞ合計が810に到達', '★', 810, 'like_count_total', 'legend'),
('search_1', 'ここ掘るのは得だゾ〜', '検索を初めて実行', '探', 1, 'search_count', 'normal')
ON CONFLICT (code) DO NOTHING;

-- 語録55語（schema-v2.sql 30語 ＋ schema-v2.1.sql 25語）
INSERT INTO quotes (text, reading, category, source, meaning, usage_note) VALUES
('いいよ、来いよ！', 'いいよこいよ', 'wild', '淫夢四章', '野獣先輩の最有名語録。数字では114514。', '誘いを受け入れる時に。胸にかけて！胸に！'),
('114514', 'いいよこいよ', 'number', '淫夢語録', '「いいよ、来いよ」の語呂合わせ。最重要数字。', '金額・回数・IDなど何にでも仕込む文化。'),
('810', 'やじゅう', 'number', '淫夢語録', '「野獣」の語呂。野獣先輩の代名詞。', '8月10日＝野獣の日。'),
('こ↑こ↓', 'ここ', 'wild', '淫夢四章', '野獣邸を指し示した名言。表記は今も論争中。', '場所や対象を指示する時に。'),
('24歳、学生です。', 'にじゅうよさいがくせいです', 'wild', '変態面接官S17', '野獣先輩の自己申告プロフィール。', '自己紹介の定型テンプレ。'),
('やりますねぇ!', 'やりますねぇ', 'wild', 'Discovery第六号', '急に大声で返した質問への回答。', '褒め言葉としても使われる。'),
('ンアッー!', 'んあっー', 'imn', '淫夢語録', '淫夢語録の代名詞的存在。', '驚きや絶頂時の悲鳴。'),
('やったぜ。', 'やったぜ', 'common', '変態糞親父', '成功を確信した時の台詞。', '達成感と共に打つべし。'),
('微レ存…？', 'びれぞん', 'common', '淫夢民会話', '「微粒子レベルで存在している…？」の略。', '可能性が低いがゼロではない時に。'),
('ファッ!?', 'ふぁっ', 'common', '淫夢一章', '想定外に驚いた時の悲鳴。', '淫夢1発目の野獣の悲鳴が由来。'),
('草不可避', 'くさふかひ', 'common', '淫夢民会話', '爆笑が避けられないこと。', '草文化の元祖的一つ。'),
('小並感', 'こなみかん', 'common', '淫夢語録', '「小学生並みの感想」の略。', '感想が稚拙な時の自虐・ツッコミに。'),
('あっ…(察し)', 'あっさし', 'common', '淫夢語録', 'まずいものを察した時。', '野獣の「24歳学生」発言への反応が由来。'),
('†悔い改めて†', 'くいかいあらためて', 'wild', '淫夢四章空耳', '「いいよ、上がって上がって」の空耳。', '戒める時に。†で囲むのが正式表記。'),
('ありがとナス', 'ありがとなす', 'imn', 'KBTIT', '「ありがとうございます」の滑舌。', '感謝を述べる時に。'),
('オナシャス！', 'おなしゃす', 'imn', 'TDN', '「お願いします」の早口。', '依頼する時に。'),
('いいゾ〜これ', 'いいぞこれ', 'imn', 'MUR', '良いと思った時のMURのセリフ。', 'いわゆる「いいね」の意。'),
('当たり前だよなぁ?', 'あたりまえだよなぁ', 'imn', 'MUR', '当たり前の強調。', '問いかけの形で使う。'),
('はぇ^〜すっごいおっきい…', 'はぇすっごいおっきい', 'imn', '遠野', '大きい物を見た時の遠野の感想。', 'こ↑こ↓と対をなす語録。'),
('まずいですよ！', 'まずいですよ', 'imn', '遠野', '「田所さん!?ちょっとまずいですよ!」', '事態の不味さを指摘する時に。'),
('あぁ＾〜いいっすねぇ＾〜', 'あぁいいっすねぇ', 'imn', '遠野', '提案への同調。', '濁点と半角の塩梅が肝。'),
('たまげたなあ', 'たまげたなあ', 'other', 'R大野球監督', '部員のホモビ出演を確認した時の言葉。', '驚愕の Gianluigi・ Scale な表現に。'),
('あくしろよ', 'あくしろよ', 'other', 'TNOK', '「早くしろよ」の空耳。', 'ホモはせっかち。'),
('ぬわああああ疲れたもおおおおん', 'ぬわあああつかれたもん', 'wild', '迫真空手部', '空手部開幕の疲労の叫び。', '仕事・勉強の後に。'),
('イキスギィ!', 'いきすぎぃ', 'wild', '淫夢四章', '「行き過ぎ」の空耳。', '度が越している時に。'),
('これもうわかんねぇな', 'これもうわかんねぇな', 'wild', '淫夢四章', '予測が読めない時。', '日焼けの感想から。'),
('はっきりわかんだね', 'はっきりわかんだね', 'wild', '淫夢四章', '確信している時。', '「わかるんだね」は誤り。'),
('じゃけん〜しましょうね', 'じゃけんしましょうね', 'other', '淫夢語録', '予定を立てる時。', '「じゃけん夜行きましょうね〜」から。'),
('おかのした', 'おかのした', 'other', '淫夢語録', '「わかりました」の空耳。', '承諾の意。'),
('人間の鑑', 'にんげんのかがみ', 'common', '淫夢語録', '大げさに賞賛する時。対義語は人間の屑。', '偉業を成した人に。'),
('1145141919810', 'いいよこいよいくいくやじゅう', 'number', '淫夢語録', '114514+1919+810の複合神聖数字。完全勝利を意味する。', '何かを成し遂げた時に。'),
('オイル塗ろっか？', 'おいるぬろっか', 'wild', '淫夢四章', 'サンオイルを塗る時に言った野獣先輩のセリフ。', '相手を気遣う（表向き）時に。'),
('まずうちさぁ、屋上…あんだけど、焼いてかない？', 'まずうちさぁおくじょうあんだけどやいてかない', 'wild', '淫夢四章', '自宅の屋上を案内した時のセリフ。', '人を招く時に。'),
('俺もやったんだからさ', 'おれもやったんだからさ', 'wild', '淫夢四章', '行動を促す時のセリフ。', '(嫌々)(同調圧力)のタグと共に。'),
('ぬわあああああん疲れたもおおおおおん', 'ぬわあああんつかれたもん', 'wild', '迫真空手部', '空手部の開幕を飾る絶叫。', '労働・勉強後の投稿に。'),
('お前のことが好きだったんだよ！', 'おまえのことがすきだったんだよ', 'wild', '淫夢四章', '野獣先輩の切実な告白。', '推しへる愛を語る時に。'),
('アイスティーしかなかったけどいいかな？', 'あいすてぃーしかなかったけどいいかな', 'wild', '淫夢四章', '睡眠薬入りの飲み物を勧める前振り。', '来客をもてなす時に（※飲み物は健全なものを）。'),
('見とけよ見とけよ〜', 'みとけよみとけよ', 'wild', '淫夢四章', '何かを見せつける時のセリフ。', '自慢したい時に。'),
('Foo↑気持ちぃ〜', 'ふーきもちぃ', 'wild', '淫夢語録', '悦に浸る時の表現。', 'リラックスした場面で。'),
('ま、多少はね？', 'ましょうだはね', 'wild', '淫夢語録', '多少は許容する趣旨。', '妥協を表明する時に。'),
('あん、いい風呂', 'あんいいふろ', 'wild', '迫真空手部', '入浴時の感想（空耳）。', 'お風呂上がりの投稿に。'),
('バッチェ冷えてますよ', 'ばっちゃ ひえてますよ', 'other', '淫夢語録', 'ビールの冷え具合を称賛する言葉。', '飲み物が旨い時に。'),
('ビール！ビール！', 'びーるびーる', 'wild', '淫夢四章', 'ビールを要求する言葉。', '乾杯の時に。'),
('†††', 'だがーじゅう', 'wild', '淫夢語録', '野獣を表す十字。', '祈りを捧げる時に。'),
('クソザコナメクジ', 'くそざこなめくじ', 'common', '淫夢語録', '雑魚への蔑称。', '自虐や他人への冗罵に（用法注意）。'),
('ホモはせっかち', 'ほもはせっかち', 'other', '淫夢語録', '淫夢民の行動原理を表す格言。', '急かしたい時の理屈に。'),
('淫夢要素はありません', 'いんむようそはありません', 'common', '淫夢厨語', '淫夢と関係ないコンテンツを紹介する時の定型文。', '無関係な話題を投稿する時に。'),
('検閲済み', 'けんさつずみ', 'other', '淫夢語録', '見せられないものを表す言葉。', '伏せ字に付ける。'),
('沈黙は金', 'ちんもくはきん', 'other', '淫夢語録', 'MURの格言。', '語るより黙るべき時に。'),
('ボブは忙しい', 'ぼぶはいそがしい', 'other', '淫夢語録', 'サンジェルマン伯爵的表現。', '忙しい時の言い訳に。'),
('訴訟も辞さない', 'そしょうもじさない', 'common', '淫夢語録', '強い抗議の表明。', '本気で怒る時に（冗談で）。'),
('ファッションホモ', 'ふぁっしょんほも', 'common', '淫夢語録', '淫夢を未視聴なのに語録を使う人への揶揄。', '語録を誤用した人に（優しく）。'),
('終わり！閉廷！以上！皆解散', 'おわりへいていいじょうかいさん', 'other', '閉廷おじさん', 'すべてを終わらせる言葉。', 'スレの締めに。'),
('金!暴力!SEX!', 'かい!ぼうりょく!せっくす!', 'other', 'KBSトリオ', '淫夢界隈の三要素。', '音MAD的な投稿で。'),
('たまげたなあ', 'たまげたなあ', 'other', '淫夢語録', '驚愕を表す言葉。', '驚いた時に。');
